### ISSUE TITLE
Hotspot module not working

### ISSUE THREAD

**Issue by lomeat** [PixelExperience/docs#10]
When I turning WiFi spot, the icon becomes gray and window with spot settings
![Screenshot_20200127-214737](https://user-images.githubusercontent.com/33469504/73203721-a9307080-414e-11ea-96e8-02a776cbbe85.jpg)
 closes

**Comment by Hlcpereira** [comment]
Here is not the place to report a bug. Report to your maintainer on proper ways, like on device-specific tree repo on PE-Devices, XDA-Thread or Telegram chat.
